version: '3.8'

services:

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  server:
    depends_on:
      - mysql
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      DB_HOST: mysql
    networks:
      - backend
      - frontend

  gbvclient:
    depends_on:
      - server
    build:
      context: ./gbvclient
    ports:
      - 3000:3000
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend: